/**
 * BIG-IQ Deploy Configuration
 * API used to deploy configuration changes made on BIG-IQ or BIG-IP devices.
 *
 * OpenAPI spec version: 5.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/PropertiesDeployDifferenceTaskReference'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./PropertiesDeployDifferenceTaskReference'));
  } else {
    // Browser globals (root is window)
    if (!root.BigIqDeployConfiguration) {
      root.BigIqDeployConfiguration = {};
    }
    root.BigIqDeployConfiguration.PropertiesDeployDeviceDetails = factory(root.BigIqDeployConfiguration.ApiClient, root.BigIqDeployConfiguration.PropertiesDeployDifferenceTaskReference);
  }
}(this, function(ApiClient, PropertiesDeployDifferenceTaskReference) {
  'use strict';




  /**
   * The PropertiesDeployDeviceDetails model module.
   * @module model/PropertiesDeployDeviceDetails
   * @version 5.2
   */

  /**
   * Constructs a new <code>PropertiesDeployDeviceDetails</code>.
   * @alias module:model/PropertiesDeployDeviceDetails
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>PropertiesDeployDeviceDetails</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/PropertiesDeployDeviceDetails} obj Optional instance to populate.
   * @return {module:model/PropertiesDeployDeviceDetails} The populated <code>PropertiesDeployDeviceDetails</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('deviceReference')) {
        obj['deviceReference'] = PropertiesDeployDifferenceTaskReference.constructFromObject(data['deviceReference']);
      }
      if (data.hasOwnProperty('differenceCount')) {
        obj['differenceCount'] = ApiClient.convertToType(data['differenceCount'], 'Integer');
      }
      if (data.hasOwnProperty('verificationErrorCount')) {
        obj['verificationErrorCount'] = ApiClient.convertToType(data['verificationErrorCount'], 'Integer');
      }
      if (data.hasOwnProperty('verificationCriticalErrorCount')) {
        obj['verificationCriticalErrorCount'] = ApiClient.convertToType(data['verificationCriticalErrorCount'], 'Integer');
      }
      if (data.hasOwnProperty('postDeploymentErrorCount')) {
        obj['postDeploymentErrorCount'] = ApiClient.convertToType(data['postDeploymentErrorCount'], 'Integer');
      }
      if (data.hasOwnProperty('hostname')) {
        obj['hostname'] = ApiClient.convertToType(data['hostname'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {module:model/PropertiesDeployDifferenceTaskReference} deviceReference
   */
  exports.prototype['deviceReference'] = undefined;
  /**
   * @member {Integer} differenceCount
   */
  exports.prototype['differenceCount'] = undefined;
  /**
   * @member {Integer} verificationErrorCount
   */
  exports.prototype['verificationErrorCount'] = undefined;
  /**
   * @member {Integer} verificationCriticalErrorCount
   */
  exports.prototype['verificationCriticalErrorCount'] = undefined;
  /**
   * @member {Integer} postDeploymentErrorCount
   */
  exports.prototype['postDeploymentErrorCount'] = undefined;
  /**
   * @member {String} hostname
   */
  exports.prototype['hostname'] = undefined;



  return exports;
}));


